# Site settings
author: Nicole Sims
title: Why did I decide to learn Software Engineering 
header-img: img/home-bg.png
email: nssims105@gmail.com
copyright_name: Nicole Sims
description: > # this means to ignore newlines until "baseurl:"
  To be or not to be?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nssims

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
